# Generated by Django 6.0.4 on 2026-05-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_product_new_category_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of additional product image URLs'),
        ),
    ]
