# Generated by Django 6.0.5 on 2026-06-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_activation_guidance_product_bracelet_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Enter sizes separated by commas (e.g., S, M, L, XL)', max_length=255),
        ),
    ]
