# Generated by Django 6.0.5 on 2026-06-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_product_sizes_productsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='standard_chain_sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='standard_preferable_chain_sizes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
