# Generated by Django 6.0.5 on 2026-06-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_product_standard_chain_sizes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='customized/')),
                ('badge', models.CharField(blank=True, help_text='e.g., Bestseller, Premium, New', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
