# Generated by Django 6.0.5 on 2026-06-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_customizedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
