# Generated by Django 6.0.5 on 2026-06-29 05:38

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('hero_quote', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
            },
        ),
        migrations.CreateModel(
            name='ComponentsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='THE ANATOMY OF SACRED CRAFT', max_length=200)),
                ('subtitle_part_1', models.CharField(default='Components of', max_length=200)),
                ('subtitle_part_2', models.CharField(default='Rakshapotli', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Components Section',
                'verbose_name_plural': 'Components Sections',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Get in Touch', max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('business_details_title', models.CharField(default='Business Details', max_length=200)),
                ('business_details_subtitle', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('hours', models.CharField(blank=True, max_length=100)),
                ('whatsapp_support_title', models.CharField(default='WhatsApp support', max_length=200)),
                ('whatsapp_support_subtitle', models.TextField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Pages',
            },
        ),
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Frequently Asked Questions', max_length=200)),
                ('button_text', models.CharField(default='Connect With Us', max_length=100)),
                ('button_link', models.CharField(default='/contact', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ Section',
                'verbose_name_plural': 'FAQ Sections',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1_title', models.CharField(max_length=200)),
                ('section1_description', models.TextField()),
                ('section1_subscription_box_title', models.CharField(max_length=200)),
                ('section1_subscription_box_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Footer Section',
                'verbose_name_plural': 'Footer Sections',
            },
        ),
        migrations.CreateModel(
            name='FooterMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer Menu',
                'verbose_name_plural': 'Footer Menus',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='GoldSilverSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver')], help_text='Identifier for the section (Gold or Silver)', max_length=10, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('title_suffix', models.CharField(default='Collection', help_text="e.g., 'Collection'", max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(help_text='Background image for the section', upload_to='goldsilver/')),
                ('button_text', models.CharField(default='EXPLORE', max_length=50)),
                ('button_link', models.CharField(help_text='URL link for the button (e.g., /shop/gold)', max_length=200)),
                ('title_color', models.CharField(default='#000000', max_length=7)),
                ('collection_color', models.CharField(default='#000000', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('line_color', models.CharField(default='#000000', max_length=7)),
                ('button_bg_color', models.CharField(default='#000000', max_length=7)),
                ('object_position', models.CharField(default='object-center', help_text="Tailwind class for image positioning (e.g., 'object-bottom')", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gold/Silver Section',
                'verbose_name_plural': 'Gold/Silver Sections',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal title for identifying the slide', max_length=200)),
                ('slider_image', models.ImageField(help_text='Recommended size: 1920x800px', upload_to='homepage/slider/')),
                ('text', models.TextField(blank=True, help_text='Main text/headline for the slide')),
                ('subtitle', models.CharField(blank=True, help_text="Subtitle text, e.g., 'GOLD | SILVER | DIAMONDS'", max_length=200)),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Color of the main text (hex code, e.g., #FFFFFF)', max_length=7)),
                ('text_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('text_size', models.CharField(blank=True, help_text="CSS font-size value for the main text (e.g., 'clamp(32px, 5.5vw, 84px)')", max_length=100)),
                ('button_1_text', models.CharField(blank=True, max_length=50)),
                ('button_1_link', models.URLField(blank=True)),
                ('button_1_color', models.CharField(default='#000000', help_text='Background color of button 1 (hex code)', max_length=7)),
                ('button_1_size', models.CharField(blank=True, help_text='Tailwind classes for button 1 font size', max_length=100)),
                ('button_2_text', models.CharField(blank=True, max_length=50)),
                ('button_2_link', models.URLField(blank=True)),
                ('button_2_color', models.CharField(default='#FFFFFF', help_text='Background color of button 2 (hex code)', max_length=7)),
                ('button_2_size', models.CharField(blank=True, help_text='Tailwind classes for button 2 font size', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of the slide on the homepage (0 is first)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to hide the slide without deleting it')),
            ],
            options={
                'verbose_name': 'Homepage Slide',
                'verbose_name_plural': 'Homepage Slides',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='LuxuryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(help_text='Main image for the collection page', upload_to='luxury/collections/')),
                ('video_url', models.URLField(blank=True, help_text='Optional video URL for the collection', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OccasionsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Find the Perfect Rakshapotli for Every Occasion', max_length=200)),
                ('subtitle', models.CharField(default="Thoughtfully curated gifts for life's beautiful moments.", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Occasions Section',
                'verbose_name_plural': 'Occasions Sections',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('last_updated', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Human Impressions', max_length=100)),
                ('subtitle', models.CharField(default='Lived Experiences', max_length=100)),
                ('bottom_text', models.CharField(default='Blessed Globally', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Testimonials Section',
                'verbose_name_plural': 'Testimonials Sections',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('content', ckeditor.fields.RichTextField()),
                ('image_position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', max_length=5)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.aboutpage')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ComponentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.CharField(help_text="The two-digit number, e.g., '01'", max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='rakshapotli_components/')),
                ('icon_name', models.CharField(help_text="Name of the lucide-react icon (e.g., 'Gem', 'Sparkles')", max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.componentssection')),
            ],
            options={
                'verbose_name': 'Component Card',
                'verbose_name_plural': 'Component Cards',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='api.faqsection')),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='FooterIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Facebook, Instagram', max_length=50)),
                ('icon_class', models.CharField(help_text='e.g., fa fa-facebook, fab fa-instagram (Font Awesome classes)', max_length=100)),
                ('link', models.URLField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='api.footer')),
            ],
            options={
                'verbose_name': 'Footer Icon',
                'verbose_name_plural': 'Footer Icons',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='FooterMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.footermenu')),
            ],
            options={
                'verbose_name': 'Footer Menu Item',
                'verbose_name_plural': 'Footer Menu Items',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='FooterSecondSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_text_1', models.CharField(default='© 2026 Drishanti. Elegant Luxury.', max_length=200)),
                ('copyright_text_2', models.CharField(default='Crafted in India, Consecrated for the World.', max_length=200)),
                ('footer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_two', to='api.footer')),
            ],
            options={
                'verbose_name': 'Footer Second Section',
                'verbose_name_plural': 'Footer Second Sections',
            },
        ),
        migrations.AddField(
            model_name='footermenu',
            name='section_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='api.footersecondsection'),
        ),
        migrations.CreateModel(
            name='LuxuryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='luxury/products/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.luxurycollection')),
            ],
        ),
        migrations.CreateModel(
            name='OccasionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon_name', models.CharField(help_text="Name of the lucide-react icon (e.g., 'Baby', 'Heart')", max_length=50)),
                ('hover_image', models.ImageField(upload_to='occasions/')),
                ('link', models.CharField(default='#', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.occasionssection')),
            ],
            options={
                'verbose_name': 'Occasion Card',
                'verbose_name_plural': 'Occasion Cards',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating from 1 to 5')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='api.testimonialssection')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['display_order'],
            },
        ),
    ]
