"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env
from dotenv import load_dotenv
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-glus=gt47ng%d%myc22f)7neg%bpr_t)!3*_ozsi4g$7^ign5g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [ '127.0.0.1', 'localhost', 'drishanti.com', 'www.drishanti.com', ]

# Application definition

INSTALLED_APPS = [
    "jazzmin",

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'nested_admin', # Added for django-nested-admin
    'api',
    'ckeditor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         'DIRS': [
             os.path.join(BASE_DIR, 'dist'),
             os.path.join(BASE_DIR, 'templates'),
         ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'dist' / 'assets',
    ('images', BASE_DIR / 'dist' / 'images'),
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Razorpay configuration
RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', 'your_key_id')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', 'your_key_secret')

# CORS configuration for local frontend development
CORS_ALLOWED_ORIGINS = [
    "https://drishanti.com",
    "https://www.drishanti.com",
    "http://localhost:3000",
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:5175",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "http://127.0.0.1:5175",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
    'x-requested-with',
    'x-session-id',
]


# Jazzmin Admin Customization
JAZZMIN_SETTINGS = {
    "site_title": "Drishanti Admin",
    "site_header": "Admin",
    "site_brand": "Admin",
    "welcome_sign": "Welcome to Drishanti Admin Panel",

    "site_logo": "../images/logo.webp",
    "login_logo": "../images/logo.webp",
    "site_icon": "../images/favicon.ico",

    "show_sidebar": True,
    "navigation_expanded": True,

    "icons": {
        "api.Product": "fas fa-gem",
        "api.Category": "fas fa-folder",
        "api.SubCategory": "fas fa-folder-open",
        "api.Order": "fas fa-shopping-cart",
        "api.OrderItem": "fas fa-box",
        "api.Coupon": "fas fa-tags",
        "api.CustomizedProduct": "fas fa-star",
        "api.Wishlist": "fas fa-heart",
        "api.Cart": "fas fa-cart-plus",
        "api.ContactMessage": "fas fa-envelope",
        "api.AboutPage": "fas fa-info-circle",
        "api.ComponentsSection": "fas fa-puzzle-piece",
        "api.ContactPage": "fas fa-address-book",
        "api.FAQSection": "fas fa-question-circle",
        "api.FooterMenu": "fas fa-list",
        "api.FooterSecondSection": "fas fa-stream",
        "api.Footer": "fas fa-shoe-prints",
        "api.GoldSilverSection": "fas fa-coins",
        "api.HomepageSlider": "fas fa-images",
        "api.NewsletterSubscription": "fas fa-envelope-open-text",
        "api.OccasionsSection": "fas fa-calendar-alt",
        "api.Policy": "fas fa-file-alt",
        "api.TestimonialsSection": "fas fa-comment-alt",
    },

    "topmenu_links": [
        {"name": "Home", "url": "admin:index"},
    ],

    "order_with_respect_to": [
        "api",
    ],
}

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': 800,
        'stylesSet': [
            {
                'name': 'Quote',
                'element': 'p',
                'attributes': { 'class': 'quote' }
            }
        ]
    },
}

# Email Configurations for sending verification OTPs and order confirmations
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

